### ISSUE TITLE
Consider changing an order of AuctionId and PoolId for KVStore

### ISSUE THREAD

**Issue by queencre** [crescent-network/crescent#112]
## Summary

Currently, `AuctionId` and `PoolId` are used when storing a rewards auction. It is suggested by @lv-koala that since `PoolId` acts as `AuctionId`'s parent (e.g: auction id increments within the pool id), it is more intuitive to have `PoolId` first.

## Proposal

Change an order of `AuctionId` and `PoolId`

- RewardsAuctionKey: `[]byte{0xe5} | PoolId | AuctionId -> ProtocolBuffer(RewardsAuction)`

## Tasks

- Change an order of `AuctionId` and `PoolId` (keeper and types)
- Update CLI commands
- Update gRPC query endpoints

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kingcre** [comment]
Closed since it's outdated.
