### ISSUE TITLE
Release v5 checklists

### ISSUE THREAD

**Issue by queencre** [crescent-network/crescent#141]
## Summary

This issue contains checklists before releasing v5. Core functionality for v5 is to adopt Cosmwasm into Crescent blockchain.

## Checklists

- Ensure semantic versioning is adopted (v4 -> v5)
- Update related documents
- Update `CHANGELOG.md`

____

#### For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by kingcre** [comment]
Closing since it's outdated.
