### ISSUE TITLE
Add Slack app in repo

### ISSUE THREAD

**Issue by sgerogia** [crescent-network/crescent#27]
Hello.

We would like to get notifications of upcoming releases.

It would be a massive help if we could do it through [Github's Slack](https://github.com/apps/slack/installations/new) integration.

Could you kindly install it?

Thank you

**Comment by queencre** [comment]
@sgerogia Sorry for the late response on this. Why don't you use RSS bot?

**Comment by queencre** [comment]
I will close this issue as it is not tightly related to core.
