### ISSUE TITLE
Getting int64() out of bound error because of config

### ISSUE THREAD

**Issue by bahdotsh** [crescent-network/crescent#36]
## Summary of Bug

When the staking ratio of the chain is very disproportionate, the reward generated is very high causing the chain to break and will give this error. 

## Version

v1.0.0

## Steps to Reproduce

While setting up the genesis-account do this
```
crescentd add-genesis-account liquid1 10000000000000000000000000000000000000000stake --home liquidStaked

crescentd gentx liquid1 100000000stake --chain-id liquidStakeChain --home liquidStaked
```
And now when we liquidStake to this validator the chain will break with Int64() out of bound error

## For Admin Use

- [ ] Not duplicate issue
- [ ] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [ ] Contributor assigned/self-assigned

**Comment by queencre** [comment]
I'm sorry to reply this too late. I guess this issue is related to when starting a network? How did you set up the disproportionate staking ratio? Can you elaborate this in more detail for us?

**Comment by queencre** [comment]
@bahdotsh Appreciate for taking the time to test this out. I will close this as it is stale issue. Let me know if you encounter any issue or have some new issues.
