### ISSUE TITLE
Error: code 8

### ISSUE THREAD

**Issue by LL-Cosmo** [crescent-network/crescent#69]
Everytime I try to deposit Atom from Cosmostation IBC wallet to app.crescent I get this error msg in the picture?

Have tried to remove the Network and connection from the wallet, hard refresh but won't work.

![IMG_20221002_213458](https://user-images.githubusercontent.com/79336608/193471166-ca81615e-49d1-42e6-9b8e-cf4186288ac8.jpg)

**Comment by queencre** [comment]
This is core repository that runs Crescent Network blockchain. I suggest you to go ask Cosmostation about this issue. They will be able to give you an answer. I will close this issue as it is related to Cosmostation IBC wallet.

**Comment by LL-Cosmo** [comment]
Ok, will. Thanks
________________________________
